export {default as Home } from './Home'
export {default as Posts } from './Posts'
export {default as Profile } from './Profile'
export {default as Login } from './Login.jsx'
export {default as Register} from './Register.jsx'
export {default as Navbar } from './NavbarFolder/Navbar'